"""empty message

Revision ID: 0efa48aa8271
Revises: ab3ae4ba643c
Create Date: 2023-08-11 18:47:12.122060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efa48aa8271'
down_revision = 'ab3ae4ba643c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s1', sa.Integer(), nullable=True),
    sa.Column('s2', sa.Integer(), nullable=True),
    sa.Column('s3', sa.Integer(), nullable=True),
    sa.Column('s4', sa.Integer(), nullable=True),
    sa.Column('s5', sa.Integer(), nullable=True),
    sa.Column('s6', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slices_s1'), ['s1'], unique=False)
        batch_op.create_index(batch_op.f('ix_slices_s2'), ['s2'], unique=False)
        batch_op.create_index(batch_op.f('ix_slices_s3'), ['s3'], unique=False)
        batch_op.create_index(batch_op.f('ix_slices_s4'), ['s4'], unique=False)
        batch_op.create_index(batch_op.f('ix_slices_s5'), ['s5'], unique=False)
        batch_op.create_index(batch_op.f('ix_slices_s6'), ['s6'], unique=False)

    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('short_url',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.alter_column('short_url',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)

    with op.batch_alter_table('slices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slices_s6'))
        batch_op.drop_index(batch_op.f('ix_slices_s5'))
        batch_op.drop_index(batch_op.f('ix_slices_s4'))
        batch_op.drop_index(batch_op.f('ix_slices_s3'))
        batch_op.drop_index(batch_op.f('ix_slices_s2'))
        batch_op.drop_index(batch_op.f('ix_slices_s1'))

    op.drop_table('slices')
    # ### end Alembic commands ###
